# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "folojet"
client_id = "7f2f7fb0ffd9670eb8e100c22cd8c307"
application_url = "http://localhost:3001/api/auth"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content, write_content, read_files, write_files, unauthenticated_read_product_listings,unauthenticated_read_product_tags, read_gift_cards, read_products, read_product_listings, read_shipping, read_themes, write_themes"

[auth]
redirect_urls = [ "http://localhost:3001/api/auth/callback" ]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
dev_store_url = "folojet-dev-store.myshopify.com"
